### ISSUE TITLE
Response with array of models

### ISSUE THREAD

**Issue by Axort** [mukeshydv/VaporCleanArchitecture-Swift#1]
I was wondering how can the extension AnyUseCase can be changed to support a response with an array of models.

As of right now the AnyUseCase extension support only single objects, as expressed here...

```
extension AnyUseCase where Response: ResponseConvertible {
    func executeResponse(from request: Vapor.Request, body: Request)  -> EventLoopFuture<BaseResponse<Response.Response>> {
        let response = try await execute(request: eventLoopRequest(body, eventLoop: request.eventLoop))
            .map { BaseResponse(status: 200, message: "Success", data: $0.toResponse) }
        
    }
}
```

But when you try to get an array of models when calling the executeReponse from a UseCase, this doesn't work since it expects a single model to be returned.

Do you have any ideas on how to do this?

**Comment by mukeshydv** [comment]
This extension works for any type (as Response is a generic type) which conforms to protocol `ResponseConvertible`. You can conform any Array to `ResponseConvertible` protocol and this will work.

You can use something like:

```swift
extension Array: ResponseConvertible where Element: ResponseConvertible {
  var toResponse: [Element.Response] { 
    return map { $0.toResponse }
  }
}
```

**Comment by Axort** [comment]
Thank you, forgot to reply to this, I actually got it like this:

```
extension Array: ResponseConvertible where Element: ResponseConvertible {
    var toResponse: some Content {
        return self.map { $0.toResponse }
    }
}
```

I guess it's better to have it with `[Element.Response]` instead of `some Content` because I had to put a cast each time I wanted to return something from a use case. I'll change it as yours. 

Thanks again!
